project_id = "qefzutfaawsegmwgaynj"

[functions.fedpat-sync]
verify_jwt = false

[functions.invite-pas-producer]
verify_jwt = true

[functions.register-pas-application]
verify_jwt = false

[functions.approve-pas-producer]
verify_jwt = true

[functions.google-reviews]
verify_jwt = false

[functions.admin-mfa]
verify_jwt = true